source 'https://rubygems.org'

gem 'html-proofer', '>= 3.14.1'
gem 'jekyll', '>= 3.6.3'
gem 'jekyll-assets', '>= 3.0.12'
gem 'jekyll-avatar', '>= 0.4.0'
gem 'jekyll-coffeescript'
gem 'jekyll-feed'
gem 'jekyll-haml', '>= 0.1.4'
gem 'jekyll-language-plugin'
gem 'jekyll-mentions', '>= 1.5.1'
gem 'jekyll-scholar', '>= 5.8.2'
gem 'jekyll-scholar-extras', :github => 'jgoodall/jekyll-scholar-extras'
gem 'jekyll-seo-tag', '>= 2.0.0'
gem 'jekyll-sitemap'
gem 'jemoji', '>= 0.11.1'
gem 'nokogiri', '>= 1.11.4'
