source 'https://rubygems.org'

gem 'html-proofer', '>= 3.15.0'
gem 'jekyll', '>= 3.8.7'
gem 'jekyll-assets', '>= 2.4.0'
gem 'jekyll-avatar', '>= 0.7.0'
gem 'jekyll-coffeescript'
gem 'jekyll-feed'
gem 'jekyll-haml', '>= 1.0.0'
gem 'jekyll-language-plugin'
gem 'jekyll-mentions', '>= 1.6.0'
gem 'jekyll-scholar', '>= 5.15.0'
gem 'jekyll-scholar-extras', :github => 'jgoodall/jekyll-scholar-extras'
gem 'jekyll-seo-tag', '>= 2.7.0'
gem 'jekyll-sitemap'
gem 'jemoji', '>= 0.12.0'
gem 'nokogiri', '>= 1.10.5'
