source 'https://rubygems.org'

gem 'html-proofer'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-avatar'
gem 'jekyll-coffeescript'
gem 'jekyll-feed'
gem 'jekyll-haml'
gem 'jekyll-language-plugin'
gem 'jekyll-mentions'
gem 'jekyll-scholar'
gem 'jekyll-scholar-extras'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'nokogiri'
