#!/usr/bin/env bash

set -ev
source "$(dirname "$0")/functions"

export PLUGIN_DIR="$BASE_DIR/jekyll_plugins"

mkdir -p "$PLUGIN_DIR"
pushd "$PLUGIN_DIR"

function install-dir() {
  local DIR_NAME="$1"
  mkdir -p "$BASE_DIR/$DIR_NAME"
  local PLUGIN_NAME="$2"
  shift 2
  local ABSOLUTE_PATH
  for PLUGIN_PATH in "$@"; do
    ABSOLUTE_PATH="$PLUGIN_DIR/$PLUGIN_NAME/$PLUGIN_PATH"
    ln-if-ne "$ABSOLUTE_PATH" "$BASE_DIR/$DIR_NAME"
  done
}

export -f install-dir

function install-plugins() {
  install-dir _plugins "$@"
}

export -f install-plugins

function install-includes() {
  install-dir _includes "$@"
}

export -f install-includes

clone-or-pull 'bdesham/inline_highlight'
install-plugins 'inline_highlight' \
  'lib/jekyll_inline_highlight.rb'

clone-or-pull 'git-no/jekyll-breadcrumbs' 'v.1.0.5'
for SOURCE_DIR in _plugins _includes; do
  install-dir "$SOURCE_DIR" 'jekyll-breadcrumbs' \
    $(cd jekyll-breadcrumbs && find "$SOURCE_DIR" -mindepth 1 -maxdepth 1)
done

popd

succeed

# vim: set ft=sh ts=2 sw=2 et sta:
